[workspace]
members = ["truma-ekit-controller", "truma-ekit-core", "truma-ekit-thermostat"]

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
